# Site
title: Majid Hajian
description: My Personal website and articles on <br/>Front-End technologies such as JavaScript, Angular, React, EmberJs, NodeJs, HTML5 &...
url: https://www.majidhajian.com
logo: mj.png
locale: en_US

# Left Block Images
background:
  homepage: images/home.png

# Jekyll
permalink:          /:title/
#paginate: 5
#paginate_path:      /blog/page:num/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-85685723-1

# Social Links
#email:             email
#google.plus:        username
twitter:            mhadaily
#facebook:           username
github:             mhadaily
stackoverflow:     1921541/majid
linkedin:          mhadaily
#xing:              username
#instagram:          username
#lastfm:            username
#tumblr:            username
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
#  - jekyll-paginate

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
